### ISSUE TITLE
Training Pose Maps

### ISSUE THREAD

**Issue by ri-sal** [pse-ecn/pose-sensitive-embedding#13]
Hi, where can we find the datasets with <dataset-name>-pose-map. 

Is there a way to generate this, or do you offer the dataset?

**Comment by ssarfraz** [comment]
pose maps are the output of of deepercut model as explained in the readme (see also our paper). These 14 channels joint locations are appended to the RGB image to have 17 channel input. 
To deploy the shared PSE models you need to prepare similarly the input for your market or duke test images.

**Comment by ri-sal** [comment]
Thanks. Just to clarify, by 'pose map', do you mean the scmap (size (64,36,14)) as mentioned in the pose-tensorflow implementation (https://github.com/eldar/pose-tensorflow/blob/master/demo/singleperson.py) ?

**Comment by ssarfraz** [comment]
Hi,  I have added the posemaps generator and writer script here (https://github.com/pse-ecn/pose-sensitive-embedding/blob/master/tools/images_to_pose_maps.py). 

Copy this file inside the Deeper Cut Repository and try to run it with the required command line arguments, which are defined in the main(). 

python3 images_to_pose_maps.py --input-pattern=/path/to/the/images/*.jpg --output-dir=/path/to/save/posemaps

**Comment by ri-sal** [comment]
Hi, thank you for the script.

I have the following error:

Traceback (most recent call last):
  File "images_to_pose_maps.py", line 17, in <module>
    from demo.utils import pose_map_to_image, heat_map_to_image
ModuleNotFoundError: No module named 'demo.utils'

**Comment by ssarfraz** [comment]
looks like deeprcut have removed the util file from their repo, anyways I have update our script here https://github.com/pse-ecn/pose-sensitive-embedding/blob/master/tools/images_to_pose_maps.py

try it , it should work now.

**Comment by ri-sal** [comment]
Thank you for uploading the scripts. I tried to train evaluate the Pose Only approach but again (similar to #14), I am not able to reproduce the published results.

Here are my steps:

**Training a Resnet-50 Baseline on Market1501**

python3 trainer_preid.py --output='output_prid' --data='/mnt/Datasets/Incoming/Surveillance/PRID/Market-1501/data/Market-1501-v15.09.15/' --dataset-name=market1501 --batch-size=16 --num-epochs=100 --network-name=resnet_v1_50 --initial-checkpoint='./checkpoints/resnet_v1_50.ckpt' --checkpoint-exclude-scopes=resnet_v1_50/logits --trainable-scopes=resnet_v1_50/logits --no-evaluation

**Training Pose Map Models**

python3 images_to_pose_maps.py --input-pattern=/path/to/the/images/*.jpg --output-dir=/path/to/save/posemaps

python3 trainer_preid.py --output='output_pose_maps' --data='/mnt/Projects/CV-008_Students/srl4hi/market1501-pose/'  --dataset-name=market1501-pose-maps --batch-size=16 --num-epochs=100 --network-name=resnet_v1_50 --initial-checkpoint='/home/srl4hi/PycharmProjects/pose-sensitive-embedding-master_1.3/output_prid/model.ckpt-86534' --checkpoint-exclude-scopes=resnet_v1_50/logits,resnet_v1_50/conv1 --trainable-scopes=resnet_v1_50/logits,resnet_v1_50/conv1 --no-evaluation

**Training Full Network**
python3 trainer_preid.py --output='output_pose_maps_full' --data='/mnt/Projects/CV-008_Students/srl4hi/market1501-pose/'  --dataset-name=market1501-pose-maps --batch-size=16 --num-epochs=100 --network-name=resnet_v1_50 --initial-checkpoint='/home/srl4hi/PycharmProjects/pose-sensitive-embedding-master_1.3/output_pose_maps/model.ckpt-80800'  --no-evaluation

**Prediction**
python3 predictor_preid.py --model-dir='output_pose_maps_full' --data='/mnt/Projects/CV-008_Students/srl4hi/market1501-pose/' --dataset-name=market1501-pose-maps --batch-size=128 --network-name=resnet_v1_50

The evaluation results I got are as follows:

MatlabEvaluationResult(mAP=46.63885542800956, rank1=71.31828978622327, rank5=87.17339667458432, rank10=91.80522565320665, rank50=97.17933491686462)

Please let me know if I again missed any steps. Thank you!

**Comment by ssarfraz** [comment]
first, looks like you only trained the logits of resnet in your baseline training step. you need to fine tune the full model here on the target data as well. same is the case with pose maps model train step, after training the new layers, train/finetune the full model.  The same problem was before in your issue #14  too.  

It would be good to try to understand the whole thing, e.g., read the paper carefully, understand the impact of different train options etc,.

**Comment by THHHomas** [comment]
Dear author:
thanks to your excellent work.
I download the newest version of the code
I run the script "python tools/images_to_pose_maps.py   ./Data/Market-1501-v15.09.15/   ./Data/Market"
but it show the following error:
Traceback (most recent call last):
  File "tools/images_to_pose_maps.py", line 14, in <module>
    from config import load_config
ModuleNotFoundError: No module named 'config'

**Comment by ssarfraz** [comment]
hi,

you need to place this file inside the downloaded deepecut repo  to extract
the pose maps.
deepcut can be cloned here https://github.com/eldar/pose-tensorflow
