### ISSUE TITLE
ModuleNotFoundError: No module named 'matlab.engine'; 'matlab' is not a package` 

### ISSUE THREAD

**Issue by swg209** [pse-ecn/pose-sensitive-embedding#27]
When I run train_preid.py, I got this error:
`Traceback (most recent call last):
  File "trainer_preid.py", line 8, in <module>
    from evaluation.evaluation_helper import get_evaluation_summary_writer
  File "/home/swg/Re-id/pose-sensitive-embedding/evaluation/evaluation_helper.py", line 5, in <module>
    import matlab.engine
ModuleNotFoundError: No module named 'matlab.engine'; 'matlab' is not a package` 
I have try ' pip install matlab'    and  'conda install matlab' ， but all fail. 
Could you please tell me how to fix this problem?  thx.

**Comment by ri-sal** [comment]
https://de.mathworks.com/help/matlab/matlab_external/install-the-matlab-engine-for-python.html

you can follow the guidelines here

**Comment by ravi7248** [comment]
> When I run train_preid.py, I got this error:
> `Traceback (most recent call last): File "trainer_preid.py", line 8, in <module> from evaluation.evaluation_helper import get_evaluation_summary_writer File "/home/swg/Re-id/pose-sensitive-embedding/evaluation/evaluation_helper.py", line 5, in <module> import matlab.engine ModuleNotFoundError: No module named 'matlab.engine'; 'matlab' is not a package`
> I have try ' pip install matlab' and 'conda install matlab' ， but all fail.
> Could you please tell me how to fix this problem? thx.

Did you able to fix the problem. I am facing the same problem in same project. I am running this project on google colab.
can you tell how you fixed this problem ?

**Comment by ssarfraz** [comment]
hi,
Matlab evaluation during training is only optional (just to see the improvements on final task during training). You really do not need to do it. just comment line 8 in trainer_preid.py, and set do_evaluation=False.  once you have trained the model you can run evaluation later on your local machine. Besides you can also replace this with equivalent python evaluation scripts (see on Market or Duke git to find one)
